#!/usr/bin/python

# 
# A simple script to basically call hg parent on the directory where macHg is being built to get the changeset id.
# Then change the key BuildHashKey in info.plist to the new changeset id key we just obtained.
# In the following You can switch the sys.exit(0) and sys.exit(1) to get the effect you want:
# sys.exit(0) will stop the script but allow compilation to continue
# sys.exit(1) will stop the script and stop the build.
#

import os, subprocess, re, sys


targetBuildDir = os.getenv("TARGET_BUILD_DIR")
if  not os.path.exists(targetBuildDir):
	print "Cannot locate target build directory"; sys.exit(0)

localHg = os.path.join(targetBuildDir, "MacHg.app/Contents/Resources/localhg")

if  not os.path.exists(localHg):
	print "Cannot locate MacHg.app/Contents/Resources/localhg"; sys.exit(0)

getChangeset = subprocess.Popen(localHg + ' parent --template "{node|short}" --cwd ' + targetBuildDir, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)

getChangesetErrors = getChangeset.stderr.read()
if (getChangesetErrors != ""):
	print "Errors reported while determining current changeset of the Mercurial repository. Error Was:\n" + getChangesetErrors + "\n"

changeset = getChangeset.stdout.read()
if (not re.search("^[0-9a-f]{12}$", changeset)):
	print "Current changeset of the Mercurial repository is malformed"; sys.exit(0)

infoPlist = os.path.join(targetBuildDir, "MacHg.app/Contents/Info.plist")
if  not os.path.exists(infoPlist):
	print "Cannot locate MacHg.app/Contents/Info.plist"; sys.exit(1)

resultDelete  = subprocess.Popen('/usr/libexec/PlistBuddy -c "Delete BuildHashKey" ' + infoPlist, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
resultDeleteErrors = resultDelete.stderr.read()
if (resultDeleteErrors !=""):
	print "Warnings detected when deleting BuildHashKey:\n" + resultDeleteErrors

resultAdd  = subprocess.Popen('/usr/libexec/PlistBuddy -c "Add BuildHashKey string '+ changeset + '" ' + infoPlist, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
resultAddErrors = resultAdd.stderr.read()
if (resultAddErrors !=""):
	print "Warnings detected when adding BuildHashKey:\n" + resultAddErrors

print "MacHg BuildHashKey set to " + changeset
